#server:
#   port: 443
#   ssl:
#      key-store: keystore.p12
#      key-store-password: springboot
#      keyStoreType: PKCS12
#      keyAlias: tomcat

spring:
   application:
      name: demoservice
#   boot:
#    admin:
#      client:
#        url:
#        - http://localhost:9090/
#        instance:
#          service-base-url: http://localhost:8080/client
          
server:
   port: 8080

      
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    preferIpAddress: true

management:
  server:
    port: 9000
#  security:
#    enabled: false

    
##---
#spring:
#   profiles: dev
#   application:
#      name: demoservice
#server:
#   port: 9090

#---
#spring: 
#   profiles: prod
#   application:
#      name: demoservice
#server: 
#   port: 4431